Even-odd training-eval selection. Trainings.yaml linked
cms-rwth/VHccPoCo pull request #16
Opened 2024-10-18 08:49 UTC by ValVau

Added trainings.yaml link into the code. Training of BDT on even events and evaluation on odd events added

2024-10-18 12:00 UTC, andreypz requested changes
This look fine to me.
Please address the comments, and resolve conflicts.

Also, I think you have the `model.txt` and `model_DY.txt` files in the root directory of the code which are not longer needed. If that's the case, could you remove those files from the repo.

2024-10-18 12:00 UTC, andreypz commented on cfg_VHcc_WLNu.py
>                                                    f"{localdir}/params/xgboost.yaml",
Is xgboost file still needed? If not, then should be removed.

2024-10-18 12:00 UTC, andreypz commented on cfg_VHcc_ZLL.py
>                                                    f"{localdir}/params/xgboost.yaml",
Same here: xgboost file

2024-10-21 11:45 UTC, ValVau commented on cfg_VHcc_WLNu.py
>                                                    f"{localdir}/params/xgboost.yaml",
Removed

2024-10-21 11:45 UTC, ValVau commented on cfg_VHcc_ZLL.py
>                                                    f"{localdir}/params/xgboost.yaml",
Removed as well

2024-10-21 13:07 UTC, ValVau commented
Added requested changes. Waiting for further comments/ merge

2024-10-21 14:07 UTC, andreypz requested changes
Please check again.

And what about my comment on the `model.txt` files?

2024-10-21 14:07 UTC, andreypz commented on cfg_VHcc_ZLL.py
>                                                    f"{localdir}/params/xgboost.yaml",
Looks like this is not done..

2024-10-21 14:19 UTC, ValVau commented
Please, have a look at latest changes

2024-10-21 15:51 UTC, andreypz approved these changes

2024-10-21 15:51 UTC, merged