Adding new variables to the Workflow and saving the arrays
cms-rwth/VHccPoCo pull request #2
Opened 2024-05-22 12:37 UTC by ValVau

2024-05-22 12:56 UTC, andreypz commented
Thanks for making this MR.
As we discussed in the meeting, I think it would be better to have a low-pt and high-pt categories in a config file. Could you implement this?

In this case you would not need different variables for high and low regions. There will be only one variable name, just created in different sub-categories.
To implement this , you would need to modify the [TwoLepTwoJets](https://github.com/cms-rwth/VHccPoCo/blob/main/CommonSelectors.py#L39-L49) method, introducing the upper pt cut on dilepton (similar to what is done for mll cuts).
Then you would need to define two version of [these cuts](https://github.com/cms-rwth/VHccPoCo/blob/f045f35138b8f2c39e262cf6e1cd4f77a681f4c9/CommonSelectors.py#L233-L255) for lo and high pt regions.

2024-05-23 09:35 UTC, andreypz requested changes
I have added a couple more comments on this request. Please take a look @ValVau .
Also, there are conflicts of the changes wrt main branch. Could you please rebase/resolve the conflicts.

2024-05-23 09:35 UTC, andreypz commented on cfg_VHcc_ZLL.py
> +run_options = {
The run options are no longer used in this config. Could you remove this part please.
Instead the `params/run_options.yaml` can be used for additional options (that are different from default in pocket-coffea.)

2024-05-23 09:35 UTC, andreypz commented on workflow.py
> +        # Suppress FutureWarning
We should have an option in the config file to create the `root` or not. Could you introduce that as well?

2024-05-24 08:38 UTC, ValVau commented
Take a look at the new commit. There I have done as you requested: new function in the CommonSelectors, new config and changed workflow.

2024-05-27 09:06 UTC, andreypz commented
Thanks, this is probably fine for now.
Could you please resolve the conflicts and then we can merge it

2024-05-27 09:10 UTC, ValVau commented
In the second commit, CommonSelectors and cfg_ZLL include both your and my changes together, so no conflicts should arise.

2024-05-28 09:59 UTC, merged